version: '2.4'

services:
  rabbitmq:
    image: "rabbitmq:3.7"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit_user_PyconES2019
      RABBITMQ_DEFAULT_PASS: rabbit_password_PyconES2019
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 10

  string_api:
    build:
      context: StringApi/
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    environment:
      TAMARCO_YML_FILE: /opt/settings.yml
    volumes:
      - ./settings.yml:/opt/settings.yml
    restart: always

  string_operator:
    build:
      context: StringOperator/
    depends_on:
      - rabbitmq
    environment:
      TAMARCO_YML_FILE: /opt/settings.yml
    volumes:
      - ./settings.yml:/opt/settings.yml
    restart: always
