system:
  deploy_name: PyconES2019
  logging:
    profile: DEVELOP
    file: false
    stdout: true
  resources:
    amqp:
      host: rabbitmq
      port: 5672
      vhost: /
      user: rabbit_user_PyconES2019
      password: rabbit_password_PyconES2019
      connection_timeout: 10
      queues_prefix: ""
    string_api_http_server:
      host: "0.0.0.0"
      port: 8080
      debug: True